In [1]:
import numpy as np
from scipy.optimize import linprog

# -------------------------------
# STEP 1: Cost Matrix
cost = np.array([
    [6, 4, 1],
    [3, 8, 7],
    [4, 6, 5]
])

# Flatten cost matrix
c = cost.flatten()

# -------------------------------
# STEP 2: Supply and Demand
supply = np.array([40, 50, 60])
demand = np.array([20, 70, 60])

# -------------------------------
# STEP 3: Create Constraints
A_eq = []
b_eq = []

# Supply constraints
for i in range(len(supply)):
    constraint = [0] * len(c)
    for j in range(len(demand)):
        constraint[i * len(demand) + j] = 1
    A_eq.append(constraint)
    b_eq.append(supply[i])

# Demand constraints
for j in range(len(demand)):
    constraint = [0] * len(c)
    for i in range(len(supply)):
        constraint[i * len(demand) + j] = 1
    A_eq.append(constraint)
    b_eq.append(demand[j])

# -------------------------------
# STEP 4: Solve using linprog
result = linprog(c, A_eq=A_eq, b_eq=b_eq, bounds=(0, None), method='highs')

# -------------------------------
# STEP 5: Reshape result
result_matrix = result.x.reshape(cost.shape)

# -------------------------------
# STEP 6: Output
print("Optimal value (total cost):", result.fun)
print("Optimal transport plan:")
print(result_matrix)

Optimal value (total cost): 680.0
Optimal transport plan:
[[ 0.  0. 40.]
 [20. 10. 20.]
 [ 0. 60.  0.]]
